---
#===========================================================
#OWASP SAMM2 Security Practice - Environment Management
#===========================================================
#Link to the model, using its unique identifier
function: 942d679b0c9e41909f8bde728fdb1259
#Unique identifier (GUID) used to refer to this practice.
#Please generate another identifier for your specific practice.
id: 53a9cd5c2d3643f3b71e4e9d92b811e2
#Official name of this practice
name: Infrastruktur-Verwaltung (Environment Management)
#Abbreviation of this practice
shortName: EM
#A one sentence description of the security practice
shortDescription: Diese Praxis beschreibt proaktive Aktivitäten zur Verbesserung und Aufrechterhaltung der Sicherheit der Umgebungen, in denen die Anwendungen des Unternehmens betrieben werden.
#A multi-paragraph description of the security practice
longDescription: |
  Die Arbeit des Unternehmens an der Anwendungssicherheit endet nicht, sobald die Anwendung in Betrieb ist. Für die verschiedenen Elemente des von Ihnen verwendeten Technologie-Stacks werden regelmäßig neue Sicherheitsfunktionen und Patches veröffentlicht, bis sie veraltet sind oder nicht mehr unterstützt werden.

  Die meisten Technologien in einem Anwendungsstapel sind standardmäßig nicht sicher. Dies ist häufig beabsichtigt, um die Abwärtskompatibilität oder die Einfachheit der Einrichtung zu verbessern. Aus diesem Grund ist für den sicheren Betrieb des Technologie-Stacks einer Organisation die konsistente Anwendung sicherer Basiskonfigurationen auf alle Komponenten erforderlich. Die Infrastruktur-Verwaltungs (Environment Management, EM) Praxis konzentriert sich darauf, Ihre Umgebung sauber und sicher zu halten.

  Während des gesamten Lebenszyklus der Technologien, auf die Ihr Unternehmen angewiesen ist, werden Schwachstellen entdeckt, und neue Versionen, die diese Schwachstellen beheben, werden nach unterschiedlichen Zeitplänen veröffentlicht. Daher ist es unerlässlich, Berichte über Schwachstellen zu überwachen und alle betroffenen Systeme rechtzeitig und ordnungsgemäß zu patchen.
#The relative order of this practice in the business function
order: 2
#Who's the "owner" of this practice
assignee: John DiLeo
#Indication of progress to keep track of overall status
progress: 80
#Type Classification of the Document
type: Praxis
